# Generated by Django 4.1.5 on 2023-01-03 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Computer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('busy', models.BooleanField()),
                ('time_busy', models.TimeField(default='00:00:00')),
                ('price', models.IntegerField()),
            ],
        ),
    ]
