# Generated by Django 4.1.5 on 2023-01-05 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computer', '0004_remove_computer_time_busy_computer_busy_until'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='busy_until',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
