# Generated by Django 4.1.5 on 2023-01-06 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computer', '0005_alter_computer_busy_until'),
    ]

    operations = [
        migrations.AddField(
            model_name='computer',
            name='category',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='computer',
            name='busy_until',
            field=models.TimeField(default='00:00:00'),
        ),
    ]
